import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../globals.css";
import { Input } from "@/components/ui/input";
import { PlusIcon } from "lucide-react";
import Image from "next/image";
import Sidebar from "@/components/sidebar/sidebar";
import Header from "@/components/header/header";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased bg-slate-100 flex flex-col md:flex-row gap-2`}
      >
        <Sidebar />
        <main className="w-full md:w-3/4 h-screen pe-2 py-2 flex flex-col">
          <Header />
          <div className="flex-1 flex flex-col overflow-hidden">{children}</div>
        </main>
      </body>
    </html>
  );
}
