import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../globals.css";
import { Input } from "@/components/ui/input";
import { PlusIcon } from "lucide-react";
import Image from "next/image";
import Sidebar from "@/components/layouts/Sidebar/";
import Header from "@/components/layouts/Header/";
import Providers from "../providers";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased bg-slate-100`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
